# Generated by Django 4.0.6 on 2022-07-22 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_ride_options_alter_ride_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='roo',
            name='ridden_by',
            field=models.ManyToManyField(to='main_app.species'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.species'),
        ),
    ]
