# Generated by Django 4.0.6 on 2022-07-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_species_ride'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ride',
            options={'ordering': ['-duration']},
        ),
        migrations.AlterField(
            model_name='ride',
            name='species',
            field=models.CharField(max_length=100),
        ),
    ]
